name: msf
description: Get your name in your favorite movie fonts
version: 3.0.2+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_cached_fonts: ^1.0.0
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  firebase_messaging: ^12.0.1
  cached_network_image: ^3.2.1
  http: ^0.13.4
  google_mobile_ads: ^2.0.0
  facebook_audience_network: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true